### PR TITLE
Issues/394

### PR DESCRIPTION
**Pull request by LemurPwned**
Hey,
here's my suggestion to fix the trimming issue. The tests seem to pass, and the global bounds should be respected.

A suggestion perhaps to add contribution guideline (formatting etc.). 
Sorry for the initial erroneous commit -- please squash if it's ok.

### CODE REVIEW

**Comment by till-m** [comment]
Hi @LemurPwned,

thanks for your contribution.
I think this generally looks good. Two things that would improve this PR imo are additional tests that cover the specific case of #394 & checking in the `_trim()` function whether `minimum_window` and the global bounds are actually compatible, and raise `ValueError` when they aren't.

I'm not a maintainer on this project though, so this is just a personal opinion.

**Comment by LemurPwned** [comment]
Thanks @till-m -- I think these are very sensible suggestions, I'll try to implement them soon, when I get some spare time.

**Comment by bwheelz36** [comment]
@till-m of course you are a maintainer! you are doing more than anyone to keep this project maintained!

**Comment by bwheelz36** [comment]
@LemurPwned  don't worry about the tiny codecov failure, if you implement the planned changes happy to accept

**Review by till-m — APPROVED** [review]
Thanks, this looks good to me 👌

**Pull request merged**
